### ISSUE TITLE
Working with EKS ALB with knative services using kourier network

### ISSUE THREAD

**Issue by sudughonge** [knative-sandbox/net-kourier#1030]
I recently set up a knative serving environment on an EKS cluster. I'm trying to use an existing ALB-ingress combination to point to knative services I have deployed. From the installation guide that I follwed (https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml/#install-a-networking-layer), it seems like Kourier makes a separate classic load balancer service (which shows up in my AWS Load balancers list). Is there a way I can have knative not use kourier's ingress class and instead have requests go through an existing k8s ALB ingress?

Additionally, I realized all knative services deploy 3 k8s service resource: 2 ClusterIPs, and 1 ExternalName service. I was looking for an NodePort service that I thought I could drop into the ingress but since it didn't, I put the ExternalName service there. That caused calls to the assigned host path to return 405 errors. I'd appreciate any help!

**Comment by ReToCode** [comment]
Hm the cloud integration would make sure to reconfigure your load balancer when worker nodes change (scale up/down). You could use a `type: NodePort` service for Kourier and manually point your ALB to the Node-Port on all Worker nodes, but you would need to manage the target-server list list yourself.

Yes Knative creates these three services per Knative service. These are used for internal routing and configuring of our components. That is part of the current design and cannot be changed. There is an open discussion about this, to see if we can improve: https://github.com/knative/serving/issues/13201.

**Comment by mpluhar** [comment]
I think what you actually want to do is to point the ALB to Kourier. I was looking into something like that on EKS.
I ended up doing the following:

Create an ALB ingress resource an point it to kourier. Note that TLS terminates on the ALB and from there on it is HTTP traffic.

```apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/group.name: lb1
    alb.ingress.kubernetes.io/healthcheck-path: /ready
    alb.ingress.kubernetes.io/healthcheck-port: '8080'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-Res-2020-10
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-2:0123456789:certificate/1234-5799-4554-6555
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/success-codes: '404'
    alb.ingress.kubernetes.io/backend-protocol-version: HTTP2
  generation: 1
  labels:
  name: kourier
  namespace: kourier-system
spec:
  ingressClassName: alb
  rules:
  - host: hostname.of.your.kservice
    http:
      paths:
      - backend:
          service:
            name: kourier-clusterip
            port:
              number: 80
        path: /
        pathType: Prefix```

Create a kourier service of the type ClusterIP

```
apiVersion: v1
kind: Service
metadata:
  name: kourier-clusterip
  namespace: kourier-system
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: 3scale-kourier-gateway
  sessionAffinity: None
  type: ClusterIP
```

Disable HTTPS redirection as per https://knative.dev/docs/serving/services/http-protocol/

DNS for the hostname in your kservice would need to point to your ALB.

Based on some testing this seems to work ok.

**Comment by ReToCode** [comment]
Based on the comment above, this seems to resolve the issue.

/close
