### ISSUE TITLE
Kourier control is not updated when CERTS_SECRET_NAME is updated

### ISSUE THREAD

**Issue by StarpTech** [knative-sandbox/net-kourier#105]
I had to restart the 3scale-kourier-control.

**Comment by jmprusi** [comment]
Hi @StarpTech ! That shouldn't happen! Can you help us by describing a little bit more what did you do?

**Comment by StarpTech** [comment]
Sry for the incomplete bug report. As far as I remember, after following the https://github.com/knative/net-kourier/blob/05d056b1c9cc601dc2f19d882078014ec28cdbcb/README.md#setup-tls-certificate steps my cert was not set. Only after `kubectl rollout restart deploy ...` the cert was found.

**Comment by markusthoemmes** [comment]
Hey @StarpTech. I'm currently in the process of reworking Kourier a bit and was wondering if you'd be up for a chat on how we can make this feature a bit more... bulletproof.
