### ISSUE TITLE
use kourier for custom service

### ISSUE THREAD

**Issue by puneetmathur-87** [knative-sandbox/net-kourier#144]
I am deploying a custom application with knative on a kind cluster and my application uses ingress rules to route traffic to my application with a virtual hostname. I tried doing it with kourier ingress class but it doesn't identify the ingress rule and service in the backend.

Could some one help me to understand if it is possible to have other services using the same ingress?

**Comment by nak3** [comment]
Hi @puneetmathur-87 Thank you for your report. 

Could you please share the actual service and the ingress manifests you are using? I think that we can make a proper suggestion if we could see them.

**Comment by nak3** [comment]
Closing for now.
@puneetmathur-87 please feel free to re-open this if you got further information I asked before.
