### ISSUE TITLE
TestUpdate looks flaky

### ISSUE THREAD

**Issue by mattmoor** [knative-sandbox/net-kourier#152]
5 of the last 7 continuous build failures (as of now) are in TestUpdate.

Looking at a handful of them ([example](https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-sandbox-net-kourier-continuous/1294050471752765440)), they appear to be due to 503s:
```
    util.go:860: Error meeting response expectations: got unexpected status: 503, expected map[200:{}]
    util.go:860: HTTP/1.1 503 Service Unavailable
        Date: Thu, 13 Aug 2020 23:35:09 GMT
        Server: envoy
        Content-Length: 0
```

If you don't already, I'd recommend enabling Envoy's debug logging during e2e runs, so that you can examine the detailed logs post-mortem more easily.  This was pretty helpful when I was chasing similar issues in net-contour.

**Comment by mattmoor** [comment]
Looks like the source of last night's nightly flake: https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-sandbox-net-kourier-nightly-release/1294560331661578240

**Comment by nak3** [comment]
I think this issue was fixed by https://github.com/knative-sandbox/net-kourier/pull/201.
At least continuous build keeps green after that https://testgrid.knative.dev/net-kourier#continuous. We will keep watching a few days and close this issue if we have not seen it.

**Comment by nak3** [comment]
Since https://github.com/knative-sandbox/net-kourier/pull/201 was merged (5 days ago),  both continuous and nightly tests passed the TestUpdate.
Let's close this for now.
