### ISSUE TITLE
Enable Alpha tests

### ISSUE THREAD

**Issue by mattmoor** [knative-sandbox/net-kourier#155]
There are two kingress conformance tests not covered by the main entrypoint by default.

Consider passing `--enable-beta` (nothing yet) and `--enable-alpha` (2 more tests) here: https://github.com/knative-sandbox/net-kourier/blob/fcba41092e623a5adc46d563fbbe6705aadae6fb/test/e2e-tests.sh#L24-L26

**Comment by mattmoor** [comment]
For example: https://github.com/knative-sandbox/net-istio/pull/226

**Comment by markusthoemmes** [comment]
Done!
