### ISSUE TITLE
High memory consumption after enabling AutoTLS

### ISSUE THREAD

**Issue by lanceliuu** [knative-sandbox/net-kourier#189]
We are using wildcard certificates per namespace. During our tests after creating ~200 ksvcs in 20 namespace, the memory usage for kourier gateway reaches ~3GB
```
kubectl -n kourier-system top pods
NAME                                      CPU(cores)   MEMORY(bytes)
3scale-kourier-gateway-6579576fff-dg5f5   749m         3350Mi
3scale-kourier-gateway-6579576fff-h6g2j   923m         3058Mi
3scale-kourier-gateway-6579576fff-j8nnf   946m         2987Mi
3scale-kourier-gateway-6579576fff-t5mdv   846m         3084Mi
3scale-kourier-gateway-6579576fff-txhs4   910m         3084Mi
3scale-kourier-gateway-6579576fff-vztdx   822m         3354Mi
```
Seems that kourier is registering tls context for each knative service regardless whether they share the same certificate data or not.

**Comment by markusthoemmes** [comment]
@lanceliuu do you reckon you could take the referenced PR for a test ride and see if it fixes the problem as advertised?

**Comment by lanceliuu** [comment]
I will do the tests and update later.
