### ISSUE TITLE
Possible envoy overloading during sequential service creation test

### ISSUE THREAD

**Issue by xliuxu** [knative-sandbox/net-kourier#193]
During performance test with 10k ksvcs created sequentially with 5s interval, we noticed that there are some peak for the route ready time (delta value of route creation time and ready time). Seems to be the same root cause of istio mentioned in https://github.com/istio/istio/issues/25685#issuecomment-687453380

![image](https://user-images.githubusercontent.com/62631896/93550299-b03a1680-f99d-11ea-8b67-19bffb6a38aa.png)
The scale of vertical axis is seconds.

**Comment by markusthoemmes** [comment]
Do you mind rerunning this test with the latest HEAD? I'd love if we dig through the bottom of this and actually root cause it.

**Comment by lanceliuu** [comment]
Sure. I will do another round of tests using head commit

**Comment by markusthoemmes** [comment]
@lanceliuu any news?

**Comment by markusthoemmes** [comment]
@lanceliuu Friendly ping :)
