### ISSUE TITLE
Test net-kourier with non-default cluster suffix

### ISSUE THREAD

**Issue by tcnghia** [knative-sandbox/net-kourier#235]
In knative/networking#209 we allow the cluster suffix to be specified.

Once net-kourier tests are on KinD we can use a similar workflow to that of https://github.com/knative-sandbox/net-contour/actions/runs/296836515/workflow to test with a non-default cluster suffix.

**Comment by markusthoemmes** [comment]
We're doing this now!

https://github.com/knative-sandbox/net-kourier/blob/233c9ce347dde9fdb4252848d9cf747a9697c91d/.github/workflows/kind-e2e.yaml#L169
