### ISSUE TITLE
Remove header and other custom envoy configuration

### ISSUE THREAD

**Issue by ivanmartinvalle** [knative-sandbox/net-kourier#404]
Love the simplicity of this project. However I'm not sure how to get passed this particular issue.

I'm wanting to remove the following headers from the Kourier response:

```sh
server: envoy
x-envoy-upstream-service-time: 10
```

Am I correct in understanding that Kourier makes this impossible? Any thoughts on adding an option to (somehow) provide custom envoy configuration?

I'm really looking for a knative serving ingress that does very little and this is almost perfect. But even at its base, envoy is doing a little too much and I feel like I need to be able to get in there and turn certain things off.

**Comment by markusthoemmes** [comment]
I think we could totally make it drop these headers to completely hide the fact it's using envoy under the hood :). I don't even see a reason not to do this in the default config.
