### ISSUE TITLE
support for httpProtocol: "Redirected"

### ISSUE THREAD

**Issue by mjgallag** [knative-sandbox/net-kourier#428]
[httpProtocol: "Redirected"](https://github.com/knative/networking/blob/94433ab7f6202fa21049dde4afa5af6cfb25b705/config/config-network.yaml#L106)

In the interim, a workaround to enable this directly in kourier would be greatly appreciated, thanks!

**Comment by nak3** [comment]
The option should be supported by https://github.com/knative-sandbox/net-kourier/pull/619.
