### ISSUE TITLE
No way to change default timeout for envoy

### ISSUE THREAD

**Issue by ovkhasch** [knative-sandbox/net-kourier#430]
I am using openshift serverless which is knative+kourier. Any long-running request being sent to knative services always timeout in 5 min and return 408 because of the default envoy stream_idle_timeout setting:

```
sh-4.4# curl -i -H "x-envoy-upstream-rq-timeout-ms: 400000000" sample.knative-serving.svc.cluster.local?sleep=200000000
HTTP/1.1 408 Request Timeout
content-length: 14
content-type: text/plain
date: Mon, 01 Feb 2021 22:34:52 GMT
server: envoy
```  

x-envoy-upstream-rq-timeout-ms header for some reason is ignored as well, timeout is always 5min. Looks like it is not possible to contol the timeout, knative revision timeout setting is ignored as well. 

It would be nice to be able to set at least a global timeout value for envoy to override the default 5min timeout.

**Comment by markusthoemmes** [comment]
Are you certain this timeout is sent by Envoy? What's the request timeout setting on the respective Knative Service? IIRC their default timeouts are 5min.
