### ISSUE TITLE
Installation issue with pre-installed Serverless 

### ISSUE THREAD

**Issue by utherp0** [knative-sandbox/net-kourier#446]
I'm starting with an OCP Cluster that has serverless (1.12.0) installed - I am installing kafka and then kourier and kourier fails to start.

Script (nabbed from Matthias) for adding Kafka:

https://raw.githubusercontent.com/rhdemo/2021-demo-cluster-setup/master/backend/strimzi.sh

Script (nabbed from Matthias) for adding Kourier:

https://raw.githubusercontent.com/rhdemo/2021-demo-cluster-setup/master/backend/kourier.sh

The 3scale-kourier-gateway-xxx Pod hangs with:

[2021-02-12 11:24:50.340][1][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:92] StreamAggregatedResources gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure

**Comment by markusthoemmes** [comment]
If you'er using Openshift Serverless, you shouldn't setup Kourier manually at all anyway. That's done for you via the Serverless Operator already.

**Comment by utherp0** [comment]
This is for provisioning Brokers for knative with Kafka channels rather than in-memory; I installed the serverless operator, instantiated the eventing and serving components and now want to replace my in memory Brokers with Kafka based ones; AFAIK this functionality is not installed as part of the serverless operator?

**Comment by markusthoemmes** [comment]
That piece I don't know of. Kourier (where this issue has been opened) though, is definitely installed already.

**Comment by matzew** [comment]
Right - like Markus says: If Openshift Serverless (especially knative-serving) is already installed, no need to install Kourier again.

/close
