### ISSUE TITLE
Finalization logic seems incorrect

### ISSUE THREAD

**Issue by mattmoor** [knative-sandbox/net-kourier#448]
I'm looking at this logic here:
https://github.com/knative-sandbox/net-kourier/blob/48320f242b9a2a8fd09d4c5ca29a0f0bfd447046/pkg/reconciler/ingress/ingress.go#L95-L110

The use of finalizers here seems both overkill and buggy, I'll try to elaborate on both facets of this below.

The use of finalizers here is overkill because we're just trying to make sure that the *in-memory* index is updated to note the removal of the kingress.  Finalizers are generally needed when state outside of the controller process needs cleaning up, and that's not the case here.

The use of finalizers here is buggy because only the "main" controller is guaranteed to process the deletion (since it removes the finalizer itself).

My recommendation here would be that since both the informer cache and the envoy configuration index are both in-memory, that it is both necessary and sufficient to directly delete the configuration in the `DeleteFunc` informer event and drop the use of finalizers here.  We (@vaikas) made a similar change to the in-memory channel in eventing relatively recently for similar reasons.

**Comment by markusthoemmes** [comment]
Sounds fair enough!

**Comment by markusthoemmes** [comment]
Actually, this go me thinking: If we add a Deletion handler, we are not guaranteed to not race already running reconciles, right? I.e. an update immediately followed by a delete **could** cause the update to be slower than the delete, because the delete doesn't go via the queue :thinking:.

Moreover: Should we remove the `ObserveFinalize` function if it's not guaranteed to observe the finalization?

**Comment by mattmoor** [comment]
So I think there's two potential "races":
1. Update queues a key, which is deleted before it is processed (should be ok because when we fetch from lister it will be missing and elide processing).
2. Update queues a key, we start to process it and while processing it the key is deleted (potentially problematic if clearing / updating the programming happen in the wrong order).

One option would be to pass a callback to `UpdateInfoForIngress` where it could ensure the continued existence of a kingress while the programming lock (which I'm assuming exists 😅 ) is held.

Some other options come to mind (e.g. a non-Finalizer-based delete flow), but I'm not sure any of those are particularly easy given a variety of the assumptions our reconciliation framework is based around (e.g. queue the key and refetch from the lister cache).


> Should we remove the ObserveFinalize function if it's not guaranteed to observe the finalization

🤷  I think you are probably right, and this was a tad overzealous in the original design.  With the benefit of hindsight, I think that basically anyone using these methods is probably using them incorrectly, which is a great reason to remove them.  Do you want to open an issue for 0.22 in pkg?

**Comment by markusthoemmes** [comment]
Can do (re opening an issue for 0.22).

Maybe we can also offer similar callbacks for the "get-but-not-found-so-i-guess-deleted" flow? I.e. an `Deleted`/`ObserveDeleted` set of functions that determine deletion via the mechanism we're after here? That'd remove the potential races I think.

**Comment by mattmoor** [comment]
Let's discuss in the other issue 😇
