### ISSUE TITLE
Stop using deprecated function from go-control-plane

### ISSUE THREAD

**Issue by nak3** [knative-sandbox/net-kourier#618]
These functions should be cleaned up.

https://github.com/knative-sandbox/net-kourier/blob/c722ae9333fc0b9b1a0af2c699be7fe094f3818c/pkg/config/ext_authz.go#L101-L102

https://github.com/knative-sandbox/net-kourier/blob/c722ae9333fc0b9b1a0af2c699be7fe094f3818c/pkg/envoy/api/cluster.go#L51-L52

https://github.com/knative-sandbox/net-kourier/blob/c722ae9333fc0b9b1a0af2c699be7fe094f3818c/pkg/envoy/api/cluster_test.go#L40-L41

https://github.com/knative-sandbox/net-kourier/blob/c722ae9333fc0b9b1a0af2c699be7fe094f3818c/pkg/envoy/api/cluster_test.go#L47-L48

**Comment by nak3** [comment]
I tried to solve and it seems https://github.com/knative-sandbox/net-kourier/pull/621/commits/ef9a82cfba8c7da33014d1f269723af34a2f9715 works fine with envoy 1.7+.

However envoy 1.6 and maistra 2.0 hit https://github.com/envoyproxy/envoy/issues/14272 as:

```
$ kubectl -n knative-serving logs net-kourier-controller-674c6867d7-vdn6m
  ...
{"severity":"INFO","timestamp":"2021-09-11T02:55:57.669081619Z","logger":"net-kourier-controller","caller":"ingress/controller.go:114","message":"Error pushing snapshot to gateway: code: 13 message Error adding/updating cluster(s) serving-tests/ingress-conformance-basics-http2-xhzpxolc: Didn't find a registered network or http filter implementation for name: 'envoy.extensions.upstreams.http.v3.HttpProtocolOptions'"}
```

It seems we just need to wait for envoy 1.7+ upgrade.

**Comment by markusthoemmes** [comment]
Ack, guess it's not too much of an issue to just leave it as-is for now. Do we know when the deprecated API will be dropped for good>

**Comment by nak3** [comment]
As per envoy doc, it is deleted across major API versions so v4 API will do that.

https://github.com/envoyproxy/envoy/blob/main/CONTRIBUTING.md#breaking-change-policy
> We will delete deprecated configuration across major API versions. E.g. a field marked deprecated in v2 will be removed in v3.
