### ISSUE TITLE
Massive amounts of resyncs due to errors publishing snapshots

### ISSUE THREAD

**Issue by markusthoemmes** [knative-sandbox/net-kourier#632]
```
c001b3fa-3333-437f-b088-3a9c044e7ce0/net-kourier-controller-f79f469fb-mq68r[controller]: {"severity":"info","timestamp":"2021-09-02T13:29:28.370Z","logger":"net-kourier-controller","caller":"ingress/controller.go:114","message":"Error pushing snapshot to gateway: code: 13 message route: unknown weighted cluster 'serving-tests-alt/domain-mapping-h-a-ruanyiku-00001'"}
```

Is logged 1088 times in https://prow.knative.dev/view/gs/knative-prow/logs/ci-knative-serving-kourier-stable/1433405592860364800 for example (with differing revision names)

**Comment by nak3** [comment]
I could produce the error on my local. It happens sporadically.
The error is from the validation which validates if the ClusterInfoMaps has the cluster or not:

https://github.com/envoyproxy/envoy/blob/release/v1.17/source/common/router/config_impl.cc#L956-L959

The validation is optional but we enabled and cannot drop it as per:

https://github.com/knative-sandbox/net-kourier/blob/70a31e3eceed87c44a697ebf23cd9938b74aa74f/pkg/generator/caches.go#L222-L228

And... I don't have a good idea to solve the validation error so far :sweat:

**Comment by markusthoemmes** [comment]
If I understand https://github.com/envoyproxy/envoy/issues/14060 and https://github.com/envoyproxy/envoy/issues/5174 correctly, it's a consistency thing between envoy warming up a cluster and then reading it later.

Maybe we can parse the error message and do a reverse lookup from the service-name to ingresses referencing said service and then only rereconcile those (vs. doing a global reconcile).
