### ISSUE TITLE
Can kourier be used as a IngressController for standard K8s service?

### ISSUE THREAD

**Issue by benjaminhuo** [knative-sandbox/net-kourier#702]
Can kourier be used as a IngressController for standard K8s service like other ingress controllers mentioned in https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/ by specifying IngressClass?

**Comment by nak3** [comment]
Hi @benjaminhuo  No, Kourier does not support the standard k8s service unfortunately.

**Comment by nak3** [comment]
I'm closing this as we don't have the plan to change Kourier as standard K8s service for now.
