### ISSUE TITLE
Global TLS is disabled when an KIngress is configured with a TLS secret

### ISSUE THREAD

**Issue by dprotaso** [knative-sandbox/net-kourier#740]
Serving Issue: https://github.com/knative/serving/issues/12377

Global TLS is configured here:
https://github.com/knative-sandbox/net-kourier#setup-tls-certificate

When you create a KIngress with it's own TLS secret (ie. provided by autoTLS) it elides the configured global tls cert from the envoy's filter chain.

Looks like it's elided here when the SNI listener is created
https://github.com/knative-sandbox/net-kourier/blob/87c1085d407b1a5026cd231eba64c90ca91ec7f4/pkg/generator/caches.go#L237-L256

**Comment by dprotaso** [comment]
cc @nak3 unsure who I should assign this to?

**Comment by norbjd** [comment]
Hello :wave: 

I have tested with a modified version of kourier (https://github.com/knative-sandbox/net-kourier/compare/main...norbjd:fix-tls-disabled-on-main-endpoint-when-domain-mapping-configured) where `if len(sniMatches) > 0` and `if useHTTPSListenerWithOneCert()` are not mutually exclusive, and it works correctly; at least, it solves issue https://github.com/knative/serving/issues/12377#issuecomment-1005019057.

Please tell me this fix looks correct to you, and if so, I will happily make a pull request.

**Comment by norbjd** [comment]
Hello :wave: 

I just wanted to add to https://github.com/knative/serving/issues/12377 that if I create multiple ksvc and if I apply a domain mapping to any of these ksvc, then **all** ksvc's https default urls return `OpenSSL SSL_connect: SSL_ERROR_SYSCALL`.

**Comment by norbjd** [comment]
It looks like that when configuring a domain mapping `my.great.domain.tld`, the whole `listener_8443`'s `filter_chains` (in Envoy config) is overriden and become a single object corresponding only to `my.great.domain.tld`:

```json
"filter_chains": [
 {
  "filter_chain_match": {
   "server_names": [
    "my.great.domain.tld"
   ]
  },
  "filters": [
   {
    "name": "envoy.filters.network.http_connection_manager",
    "typed_config": {
     "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
     "stat_prefix": "ingress_http",
     "rds": {
      "config_source": {
       "ads": {},
       "initial_fetch_timeout": "10s",
       "resource_api_version": "V3"
      },
      "route_config_name": "external_tls_services"
     },
     "http_filters": [
      {
       "name": "envoy.filters.http.router"
      }
     ],
     "access_log": [
      {
       "name": "envoy.file_access_log",
       "typed_config": {
        "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
        "path": "/dev/stdout"
       }
      }
     ]
    }
   }
  ],
  "transport_socket": {
   "name": "envoy.transport_sockets.tls",
   "typed_config": {
    "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext",
    "common_tls_context": {
     "tls_certificates": [
      {
       "certificate_chain": {
        "inline_bytes": "<certificate in base64>"
       },
       "private_key": {
        "inline_bytes": "W3JlZGFjdGVkXQ=="
       }
      }
     ],
     "alpn_protocols": [
      "h2",
      "http/1.1"
     ]
    }
   }
  }
 }
]
```

Because of this, all https requests (other than https://my.great.domain.tld) coming to this listener are not handled because this config misses the "default" case. If we had this "default" case, we obtain something like:

```json
"filter_chains": [
 {
  "filter_chain_match": {
   "server_names": [
    "my.great.domain.tld"
   ]
  },
  "filters": [
   // same as above
  ]
 },
 // possibly other filter chain objects (with different filter_chain_match)
 // and below, the "default" filter chain
 {
  "filters": [
   {
    "name": "envoy.filters.network.http_connection_manager",
    "typed_config": {
     "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
     "stat_prefix": "ingress_http",
     "rds": {
      "config_source": {
       "ads": {},
       "initial_fetch_timeout": "10s",
       "resource_api_version": "V3"
      },
      "route_config_name": "external_tls_services"
     },
     "http_filters": [
      {
       "name": "envoy.filters.http.router"
      }
     ],
     "access_log": [
      {
       "name": "envoy.file_access_log",
       "typed_config": {
        "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
        "path": "/dev/stdout"
       }
      }
     ]
    }
   }
  ],
  "transport_socket": {
   "name": "envoy.transport_sockets.tls",
   "typed_config": {
    "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext",
    "common_tls_context": {
     "tls_certificates": [
      {
       "certificate_chain": {
        "inline_bytes": "<default certificate (defined in CERTS_SECRET_NAMESPACE/CERTS_SECRET_NAME secret) in base64>"
       },
       "private_key": {
        "inline_bytes": "W3JlZGFjdGVkXQ=="
       }
      }
     ],
     "alpn_protocols": [
      "h2",
      "http/1.1"
     ]
    }
   }
  }
 }
]
```

With that said, I have forked the repo and created a version that solves this issue (see https://github.com/knative-sandbox/net-kourier/compare/main...norbjd:fix-tls-default-filter-chains). It works (without domain mapping, with 1 domain mapping, and with 2 domain mappings), but I have not created a PR because I don't know if my modification is correct and if it impacts or not the rest of kourier's behavior.

Feel free to check my commit and tell me if it's ok, I will happily create a PR then.

**Comment by nak3** [comment]
Thank you @norbjd ! I guess your approach should be fine. Could you please send the PR? It would be great if you could add the test case as well.

**Comment by norbjd** [comment]
@nak3 I have created the PR https://github.com/knative-sandbox/net-kourier/pull/743 and added some tests covering the fix! :tada:
