### ISSUE TITLE
Question: How do you tell kourier to use a static IP?

### ISSUE THREAD

**Issue by vazexqi** [knative-sandbox/net-kourier#747]
There are instructions on how to do it using istio at https://github.com/dewitt/knative-docs/blob/master/serving/gke-assigning-static-ip-address.md#step-2-update-the-external-ip-of-the-knative-ingressgateway-service however I have not been able to find anything for kourier. 

Any pointers would be appreciated.

**Comment by vazexqi** [comment]
Ah, it's just a Service of LoadBalancer underneath!
Thanks, confirming that specifying the `loadBalancerIP` value in spec works!

**Comment by theomessin** [comment]
Any way of configuring this using the Knative Operator?
