### ISSUE TITLE
HTTP Endpoint for KOURIER_EXTAUTHZ_HOST

### ISSUE THREAD

**Issue by sidharthramesh** [knative-sandbox/net-kourier#754]
I see in the [e2e tests for external authz](https://github.com/knative-sandbox/net-kourier/tree/main/test/config/extauthz) that a gRPC service is supported. Any idea this will support a HTTP service?

I'd like to use [ORY Oathkeeper](https://ory.sh/oathkeeper) as the external authenticator and it only exposes an HTTP endpoint for now.

**Comment by nak3** [comment]
/good-first-issue

We did not have the plan as nobody requested the feature. But I think it makes sense and complicated change is not necessary.
It just needs to add an option and switch the http option here - https://github.com/knative-sandbox/net-kourier/blob/37d366313782ca3ebf7b40166c278610fac72205/pkg/config/ext_authz.go#L97-L103

PR is welcome :pray:

**Comment by sidharthramesh** [comment]
Thank you @nak3. I'll try to understand the code.

According to the [Envoy docs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto.html?highlight=max_request_bytes#extensions-filters-http-ext-authz-v3-extauthz) either grpc_service (config.core.v3.GrpcService) or http_service (extensions.filters.http.ext_authz.v3.HttpService) should be set.

So I'm assuming there's also going to be some changes here?
https://github.com/knative-sandbox/net-kourier/blob/37d366313782ca3ebf7b40166c278610fac72205/pkg/config/ext_authz.go#L141-L155

I'm very new to this, and barely getting around Knative, Kourier and GoLang. So forgive me if I'm not very helpful.

**Comment by nak3** [comment]
Yes, I think you are right. Thank you!
