### ISSUE TITLE
Set no limit to the timeout by default

### ISSUE THREAD

**Issue by nak3** [knative-sandbox/net-kourier#874]
Follow up for https://github.com/knative-sandbox/net-kourier/issues/680 and https://github.com/knative-sandbox/net-kourier/pull/866

The timeout can be configured via `stream-idle-timeout` in config-kourier but the default value is still `300s` now.
So users have to configure the timeout value more than 300s when they set more than 300s `timeoutSeconds` in Knative Serving.

We probably should set the default to infinity if there are no any concerns..

_NOTE:_ The timeout of Contour and Istio are infinity by default.

**Comment by xxinran** [comment]
I'd like to fix this. 
/assign
