### ISSUE TITLE
ClusterRole should not be namespaced

### ISSUE THREAD

**Issue by Hellzed** [knative-sandbox/net-kourier#916]
Kubernetes completely ignores the "namespace" property for cluster-wide resources such as ClusterRole.

This is not an issue when using `kubectl apply`, however some tools like the [Kubernetes Provider for Terraform](https://github.com/hashicorp/terraform-provider-kubernetes#kubernetes-provider-for-terraform--) will do an extra validation step enforcing that cluster-wide resources are not namespaced, and applying the manifest will fail.

Please consider dropping the following line: https://github.com/knative-sandbox/net-kourier/blob/ad9c11ed73d5065a23c361a183490992bc110551/config/200-serviceaccount.yaml#L30

**Comment by nak3** [comment]
Hi @Hellzed Thank you for this report! 

I believe that it is no problem to delete this line.
https://github.com/knative-sandbox/net-kourier/blob/ad9c11ed73d5065a23c361a183490992bc110551/config/200-serviceaccount.yaml#L30

Could you send the PR if you don't mind?

**Comment by Hellzed** [comment]
@nak3 Done! I hope this helps.
