### ISSUE TITLE
I would like to set up kourier and external dns, how do you integrate them?

### ISSUE THREAD

**Issue by kahirokunn** [knative-sandbox/net-kourier#946]

**Comment by ReToCode** [comment]
I'm not fully sure what you mean by this. You can set up DNS like proposed in the docs: https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml/#configure-dns. Just make sure that your DNS points to the public IP (typically IP of the load balancer) of kourier. Or do you mean something different with external-dns?
