### ISSUE TITLE
Release 1.8.0 is missing release notes

### ISSUE THREAD

**Issue by mbrancato** [knative-sandbox/net-kourier#947]
There is just a placeholder saying to add the release notes:

`[add release notes here]`

https://github.com/knative-sandbox/net-kourier/releases/tag/knative-v1.8.0

**Comment by dprotaso** [comment]
/assign @nak3 

Can you back fill this?

**Comment by nak3** [comment]
Sorry for the delay. Updated the release note on 1.8.0.
