### ISSUE TITLE
Kourier controller uses deprecated exact_match for headers

### ISSUE THREAD

**Issue by mbrancato** [knative-sandbox/net-kourier#950]
Kourier 1.8.0 includes Envoy 1.21 as the image for `kourier-gateway`, however it uses features that were deprecated in 1.20.

https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.20/v1.20.0.html#deprecated

e.g.
```go
			matchHeader.HeaderMatchSpecifier = &route.HeaderMatcher_ExactMatch{
				ExactMatch: matchType.Exact,
			}
```

This causes a warning to print in the `kourier-gateway` pod for every request.

```
[2022-11-10 23:17:27.496][1][warning][misc] [source/common/protobuf/message_validator_impl.cc:21] 
Deprecated field: type envoy.config.route.v3.HeaderMatcher Using deprecated option 
'envoy.config.route.v3.HeaderMatcher.exact_match' from file route_components.proto. This configuration 
will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history 
for details. If continued use of this field is absolutely necessary, see 
https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features 
for how to apply a temporary and highly discouraged override.
```

Additionally, this is also combined with use of the deprecated `MatchSubjectAltNames`.

**Comment by nak3** [comment]
Thank you. https://github.com/knative-sandbox/net-kourier/pull/943 will fixes this but we are currently bocked by Maistra's issue. Sorry for this inconvenience.

**Comment by nak3** [comment]
Thank you for the patience. https://github.com/knative-sandbox/net-kourier/pull/943 fixed it.

/close
