### ISSUE TITLE
domain name "cluster.local" doesn't work with "kourier" but works with "kourier-internal"

### ISSUE THREAD

**Issue by daisy-ycguo** [knative-sandbox/net-kourier#984]
Is it a bug or intentional？

```
$  kubectl get svc -n kourier-system
NAME               TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
kourier            LoadBalancer   10.111.86.149    <pending>     80:32176/TCP,443:30943/TCP   187d
kourier-internal   ClusterIP      10.104.146.232   <none>        80/TCP,443/TCP               187d
$ curl -H "Host: helloworld-go.default.svc.cluster.local" 10.111.86.149
$ curl -H "Host: helloworld-go.default.svc.cluster.local" 10.104.146.232
Hello Go Sample v1!
```

The log looks like:
```
[2023-01-28T07:15:15.510Z] "GET / HTTP/1.1" 404 NR 0 0 0 - "-" "curl/7.58.0" "67c00507-b2b7-45a7-a512-f52ee106d101" "helloworld-go.default.svc.cluster.local" "-"
[2023-01-28T07:15:27.163Z] "GET / HTTP/1.1" 200 - 0 20 3 2 "-" "curl/7.58.0" "d5ba568a-87ea-4b32-9990-1fe3f9fc25a0" "helloworld-go.default.svc.cluster.local" "192.168.12.139:8012"
```

After I config a [magic DNS](https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml/#configure-dns)  "sslip.io", both internal and external work.
``` 
$ curl -H "Host: helloworld-go.default.10.111.86.149.sslip.io" 10.111.86.149
Hello Go Sample v1!
$ curl -H "Host: helloworld-go.default.10.111.86.149.sslip.io" 10.104.146.232
Hello Go Sample v1!
```

**Comment by ReToCode** [comment]
That is intentional, the `kourier-internal` is there to handle traffic inside the cluster (thus type has type `ClusterIP`) and the `kourier` service with type `LoadBalancer` can be reached from outside of the cluster (depending on your LoadBalancer infrastructure). So the cluster internal domain `*.<ns>.svc.cluster.local` is only routed in the internal kourier instance. Does this clarify things a bit?

**Comment by psschwei** [comment]
The switch to the  `svc.cluster.local` as the default domain was made in v1.8 /  https://github.com/knative/serving/pull/13259

**Comment by prein** [comment]
I hope you don't mind me commenting on an old and closed issue.
How does Kourier distinguish external requests from internal? Can I change this behavior? I want to expose a service to another cluster in the same subnet.
Also I was wondering if a 403 wouldn't be more appropriate than 404 for a request that is not served based on the source.
